import { TKey } from "interfaces";
import { useTranslation } from "next-i18next";
import Head from "next/head";
import { useRouter } from "next/router";

const Layout: React.FC<{
  children: React.ReactElement;
}> = ({ children }): React.ReactElement => {
  const { t } = useTranslation();
  const { pathname } = useRouter();

  const tit =
    pathname === "/"
      ? t("home")
      : t("home") + " | " + t(pathname?.split("/")[1] as TKey);
  return (
    <>
      <Head>
        <title>{tit}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
};

export default Layout;
